In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/sales data new.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 1.3+ MB

In [ ]:
df.isnull().sum()

User_ID                 0
Cust_name               0
Product_ID              0
Gender                  0
Age Group               0
Age                     0
Marital_Status          0
State                   0
Zone                    0
Occupation              0
Product_Category        0
Orders                  0
Amount                 12
Status              11251
unnamed1            11251
dtype: int64

In [ ]:
df.shape

(11251, 15)

In [ ]:
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN

In [ ]:
df.tail()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370.0,NaN,NaN
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367.0,NaN,NaN
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213.0,NaN,NaN
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206.0,NaN,NaN
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188.0,NaN,NaN

0        False
1        False
2        False
3        False
4        False
         ...
11246    False
11247    False
11248    False
11249    False
11250    False
Length: 11251, dtype: bool

In [ ]:
df.drop(['Status','unnamed1'],axis = 1,inplace = True)

In [ ]:
df.isnull().sum()

User_ID              0
Cust_name            0
Product_ID           0
Gender               0
Age Group            0
Age                  0
Marital_Status       0
State                0
Zone                 0
Occupation           0
Product_Category     0
Orders               0
Amount              12
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11239 entries, 0 to 11250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11239 non-null  int64
 1   Cust_name         11239 non-null  object
 2   Product_ID        11239 non-null  object
 3   Gender            11239 non-null  object
 4   Age Group         11239 non-null  object
 5   Age               11239 non-null  int64
 6   Marital_Status    11239 non-null  int64
 7   State             11239 non-null  object
 8   Zone              11239 non-null  object
 9   Occupation        11239 non-null  object
 10  Product_Category  11239 non-null  object
 11  Orders            11239 non-null  int64
 12  Amount            11239 non-null  float64
dtypes: float64(1), int64(4), object(8)
memory usage: 1.2+ MB

In [ ]:
df['Amount'] = df['Amount'].astype('int')

In [ ]:
df['Amount'].dtype

dtype('int64')

In [ ]:
df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount'],
      dtype='object')

In [ ]:
df.rename(columns = {'Marital_Status':'Shaadi'})

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Shaadi,State,Zone,Occupation,Product_Category,Orders,Amount
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188

In [ ]:
df.rename(columns = {'Shaadi':'Marital_Status'})

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,P00296942,M,18-25,19,1,Maharashtra,Western,Chemical,Office,4,370
11247,1004089,Reichenbach,P00171342,M,26-35,33,0,Haryana,Northern,Healthcare,Veterinary,3,367
11248,1001209,Oshin,P00201342,F,36-45,40,0,Madhya Pradesh,Central,Textile,Office,4,213
11249,1004023,Noonan,P00059442,M,36-45,37,0,Karnataka,Southern,Agriculture,Office,3,206
11250,1002744,Brumley,P00281742,F,18-25,19,0,Maharashtra,Western,Healthcare,Office,3,188

In [ ]:
df.describe()

            User_ID           Age  Marital_Status        Orders        Amount
count  1.123900e+04  11239.000000    11239.000000  11239.000000  11239.000000
mean   1.003004e+06     35.410357        0.420055      2.489634   9453.610553
std    1.716039e+03     12.753866        0.493589      1.114967   5222.355168
min    1.000001e+06     12.000000        0.000000      1.000000    188.000000
25%    1.001492e+06     27.000000        0.000000      2.000000   5443.000000
50%    1.003064e+06     33.000000        0.000000      2.000000   8109.000000
75%    1.004426e+06     43.000000        1.000000      3.000000  12675.000000
max    1.006040e+06     92.000000        1.000000      4.000000  23952.000000

In [ ]:
df[['Age','Orders','Amount']].describe()

                Age        Orders        Amount
count  11239.000000  11239.000000  11239.000000
mean      35.410357      2.489634   9453.610553
std       12.753866      1.114967   5222.355168
min       12.000000      1.000000    188.000000
25%       27.000000      2.000000   5443.000000
50%       33.000000      2.000000   8109.000000
75%       43.000000      3.000000  12675.000000
max       92.000000      4.000000  23952.000000

# **EDA**

Gender

In [ ]:
df.value_counts('Gender')

Gender
F    7832
M    3407
Name: count, dtype: int64

In [ ]:
df.groupby('Gender')['Amount'].sum().sort_values(ascending=False)

Gender
F    74335853
M    31913276
Name: Amount, dtype: int64

From Above Result We cansee that most of the buyers are Females and the  even the purchasing power of females is greater than men

Age

In [41]:
df.value_counts('Age Group')

Age Group
26-35    4541
36-45    2283
18-25    1879
46-50     983
51-55     830
55+       427
0-17      296
Name: count, dtype: int64

In [44]:
df.groupby(['Age Group','Gender'])['Amount'].sum().sort_values(ascending=False)

Age Group  Gender
26-35      F         30963953
36-45      F         15509956
18-25      F         11887003
26-35      M         11649489
46-50      F          6743393
36-45      M          6635038
51-55      F          5385208
18-25      M          5353729
51-55      M          2876269
46-50      M          2464451
55+        F          2404931
           M          1676056
0-17       F          1441409
           M          1258244
Name: Amount, dtype: int64

From above table we can see that most of the buyers are in age-group 26-35 and are female

**State**

In [45]:
df.columns

Index(['User_ID', 'Cust_name', 'Product_ID', 'Gender', 'Age Group', 'Age',
       'Marital_Status', 'State', 'Zone', 'Occupation', 'Product_Category',
       'Orders', 'Amount'],
      dtype='object')

In [47]:
df.value_counts('State').head(30)

State
Uttar Pradesh       1944
Maharashtra         1525
Karnataka           1304
Delhi               1104
Madhya Pradesh       921
Andhra Pradesh       811
Himachal Pradesh     608
Kerala               453
Haryana              452
Bihar                434
Gujarat              427
Jharkhand            380
Uttarakhand          320
Rajasthan            231
Punjab               200
Telangana            125
Name: count, dtype: int64

In [50]:
df.groupby(['State','Gender'])['Amount'].sum().sort_values(ascending=False)

State             Gender
Uttar Pradesh     F         13662105
Maharashtra       F         10560976
Karnataka         F          9933966
Delhi             F          8264498
Uttar Pradesh     M          5712863
Andhra Pradesh    F          5511219
Madhya Pradesh    F          5301046
Maharashtra       M          3866567
Karnataka         M          3589574
Delhi             M          3339320
Haryana           F          3198296
Himachal Pradesh  F          3163299
Gujarat           F          2832262
Bihar             F          2819281
Madhya Pradesh    M          2800096
Kerala            F          2644087
Andhra Pradesh    M          2525927
Jharkhand         F          1954275
Himachal Pradesh  M          1800069
Uttarakhand       F          1593018
Kerala            M          1250404
Rajasthan         F          1243444
Bihar             M          1203476
Gujarat           M          1113820
Jharkhand         M          1072181
Haryana           M          1021879
Punjab            F           950267
Uttarakhand       M           927926
Telangana         F           703814
Rajasthan         M           665965
Punjab            M           575533
Telangana         M           447676
Name: Amount, dtype: int64

We can see that most of the orders are from UP,Maharashtra and Karnataka and the purchasing power of women is more

Marital **Status**

In [51]:
df.value_counts('Marital_Status')

Marital_Status
0    6518
1    4721
Name: count, dtype: int64

The purchasing power of married women is more than men

In [53]:
df.value_counts('Occupation')

Occupation
IT Sector          1583
Healthcare         1408
Aviation           1310
Banking            1137
Govt                854
Hospitality         703
Media               637
Automobile          565
Chemical            541
Lawyer              531
Retail              501
Food Processing     423
Construction        414
Textile             349
Agriculture         283
Name: count, dtype: int64

In [55]:
df.groupby(['Occupation','Gender'])['Amount'].sum().sort_values(ascending=False)

Occupation       Gender
IT Sector        F         10184835
Aviation         F          9007393
Healthcare       F          8968231
Banking          F          7792295
Govt             F          6002907
IT Sector        M          4570244
Media            F          4375029
Hospitality      F          4183199
Healthcare       M          4066355
Automobile       F          3768843
Chemical         F          3665084
Aviation         M          3594905
Retail           F          3583695
Lawyer           F          3383409
Banking          M          2978315
Food Processing  F          2825277
Construction     F          2595422
Govt             M          2514305
Hospitality      M          2193206
Textile          F          2159752
Media            M          1920803
Agriculture      F          1840482
Chemical         M          1632352
Automobile       M          1599753
Lawyer           M          1598256
Food Processing  M          1245393
Retail           M          1199475
Textile          M          1045220
Construction     M          1002089
Agriculture      M           752605
Name: Amount, dtype: int64

From the above table we can see that the purchasing power of women from IT , Aviation , Banking , Healthcare is more

**Product Category**

In [56]:
df.value_counts('Product_Category')

Product_Category
Clothing & Apparel       2655
Food                     2490
Electronics & Gadgets    2087
Footwear & Shoes         1059
Household items           520
Beauty                    422
Games & Toys              386
Sports Products           356
Furniture                 352
Pet Care                  212
Office                    113
Stationery                112
Books                     103
Auto                       97
Decor                      96
Veterinary                 81
Tupperware                 72
Hand & Power Tools         26
Name: count, dtype: int64

In [57]:
df.groupby(['Product_Category','Gender'])['Amount'].sum().sort_values(ascending=False)

Product_Category       Gender
Food                   F         24176102
Footwear & Shoes       F         11534547
Clothing & Apparel     F         11479103
Electronics & Gadgets  F         11033097
Food                   M          9757781
Clothing & Apparel     M          5015916
Electronics & Gadgets  M          4610749
Footwear & Shoes       M          4040662
Furniture              F          3394642
Games & Toys           F          3045258
Sports Products        F          2675513
Furniture              M          2045409
Beauty                 F          1524257
Games & Toys           M          1286436
Auto                   F          1285791
Sports Products        M           960420
Stationery             F           891897
Household items        F           859644
Tupperware             F           830965
Stationery             M           784154
Household items        M           709693
Auto                   M           672818
Books                  M           657263
Decor                  F           596994
Beauty                 M           435227
Books                  F           404215
Pet Care               F           331509
Tupperware             M           324677
Hand & Power Tools     M           278518
Pet Care               M           150768
Decor                  M           133366
Hand & Power Tools     F           127100
Veterinary             F            90236
Office                 F            54983
                       M            26953
Veterinary             M            22466
Name: Amount, dtype: int64

the most selled products are clothing ,food and electronics

# **Conclusion :**

Married Women age group 26-35 yrs from UP,Maharashtra and Karnataka working in IT, Healthcare and Aviation are more likely to buy products from Food , Clothing and Electronics Category